name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true # Condition
    runs-on: ubuntu-latest
  
  steps:
    - name: "Checkout" # Download code from the repository
      uses: actions/checkout@v4 # Public action
      with:
        fetch-depth: 0 # Checkout all branches and tags

    - name: "Use NodeJS 18" # Download code from the repository
      uses: actions/setup-node@v3 # Public action
      with:
        node-version: '18'

    - name: "Setup npm" # Add our registry to npm config
      run: | # Custom action
        npm set @adarsh-ranjan:registry=https://npm.pkg.github.com
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
    - name: Install yarn
      run: | # Install yarn
        npm install --global yarn

    - name: Install dependencies
      run: | # Install and link dependencies
        yarn install --force
        
    - name: "Version and publish" # Interesting step
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        if [ ${{ github.base_ref }} = development ]; then
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        else
          npx lerna version --conventional-commits --conventional-graduate --yes
        fi

        npx lerna publish from-git --yes